export type ConsultationMode = 'Face-to-Face' | 'Online';

export type FacultySlot = {
  id: string;
  label: string;
  mode: ConsultationMode;
  location: string;
  enabled: boolean;
  recurring: boolean;
  ruleId?: string; // present only if generated by a recurring rule
};

export type FacultySlotsByDate = Record<string, FacultySlot[]>;

export const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export function toDateKey(date: Date): string {
  const y = date.getFullYear();
  const m = (date.getMonth() + 1).toString().padStart(2, '0');
  const d = date.getDate().toString().padStart(2, '0');
  return `${y}-${m}-${d}`;
}

export function getWeekStart(date: Date): Date {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - d.getDay());
  return d;
}

export type WeekDayInfo = {
  day: string;
  dayNum: number;
  dateKey: string;
  fullLabel: string;
  isToday: boolean;
};

export function getWeekDates(weekStart: Date): WeekDayInfo[] {
  const todayKey = toDateKey(new Date());
  const days: WeekDayInfo[] = [];
  for (let i = 0; i < 7; i++) {
    const d = new Date(weekStart);
    d.setDate(weekStart.getDate() + i);
    const dateKey = toDateKey(d);
    days.push({
      day: DAY_NAMES[d.getDay()],
      dayNum: d.getDate(),
      dateKey,
      fullLabel: d.toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
      isToday: dateKey === todayKey,
    });
  }
  return days;
}

export function formatWeekRangeLabel(weekStart: Date): string {
  const weekEnd = new Date(weekStart);
  weekEnd.setDate(weekStart.getDate() + 6);
  const startLabel = weekStart.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  const endLabel = weekEnd.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
  return `${startLabel} - ${endLabel}`;
}

export const INITIAL_FACULTY_SLOTS_BY_DATE: FacultySlotsByDate = {};